const AUDIO_EMOTION_RAILS: [(&str, &str); 7] = [
    ("happy", "Happy"),
    ("sad", "Sad"),
    ("angry", "Angry"),
    ("fearful", "Fearful"),
    ("surprised", "Surprised"),
    ("neutral", "Neutral"),
    ("uncertain", "Uncertain"),
];

fn build_audio_group_rail(
    audio_spans: &[AudioStateSpanDto],
    asr_segments: &[AsrSegmentDto],
    speech_emotion_segments: &[SpeechEmotionSegmentDto],
    sound_event_spans: &[SoundEventSpanDto],
    sound_event_detections: &[SoundEventDetectionDto],
) -> TimelineRailDto {
    let speech_rail = build_audio_speech_rail(audio_spans, asr_segments);
    let emotion_summary_rail = build_audio_emotion_summary_rail(speech_emotion_segments);
    let emotion_detail_rails = build_audio_emotion_detail_rails(speech_emotion_segments);
    let sound_events_rail = build_audio_sound_events_rail(sound_event_spans, sound_event_detections);

    let mut children = Vec::with_capacity(3);
    children.push(speech_rail);
    children.push(TimelineRailDto::group(
        "audio_emotion_summary",
        "Emotion Summary",
        "High-level polarity view of inferred speech emotion, with positive, negative, neutral, and uncertain segments shown on one lane.",
        "This is a summary layer derived from the local speech-emotion model. Confidence drives intensity, not a new continuous affect model.",
        false,
        {
            let mut nested = Vec::with_capacity(1 + emotion_detail_rails.len());
            nested.push(emotion_summary_rail);
            nested.extend(emotion_detail_rails);
            nested
        },
    ));
    children.push(sound_events_rail);

    TimelineRailDto::group(
        "audio",
        "Audio",
        "Speech, emotion, and sound-event capture grouped under one audio hierarchy for easier review.",
        "Audio keeps the current local speech, transcript, emotion, and sound-event models. This milestone reorganizes them without changing the underlying detectors.",
        false,
        children,
    )
}

fn build_audio_speech_rail(
    audio_spans: &[AudioStateSpanDto],
    asr_segments: &[AsrSegmentDto],
) -> TimelineRailDto {
    let mut slices = audio_spans
        .iter()
        .map(|span| ContextSlice {
            id: span.audio_state_span_id.clone(),
            rail: "audio_speech".to_string(),
            slice_kind: "span".to_string(),
            start_timestamp: span.first_seen_at,
            end_timestamp: span.last_seen_at.max(span.first_seen_at + 1),
            title: audio_span_title(&span.label),
            subtitle: Some(audio_span_subtitle(span)),
            source: span.source_id.clone(),
            confidence: span.avg_confidence,
            session_id: Some(span.session_id.clone()),
            app_name: None,
            window_title: None,
            interaction_state: None,
            reasons: vec![audio_span_reason(&span.label)],
            visible_windows: Vec::new(),
            ocr_preview: None,
            pii_count: 0,
            evidence_frame_path: None,
            storage_bytes: estimate_audio_span_storage_bytes(span),
            storage_exact: false,
            row_count: span.supporting_audio_chunk_ids.len() as u64,
            file_count: 0,
            has_detail_view: true,
            tags: vec!["audio".to_string(), "speech".to_string(), span.label.clone()],
        })
        .collect::<Vec<_>>();

    for segment in asr_segments {
        slices.push(ContextSlice {
            id: segment.asr_segment_id.clone(),
            rail: "audio_speech".to_string(),
            slice_kind: "event".to_string(),
            start_timestamp: segment.start_timestamp,
            end_timestamp: segment.end_timestamp.max(segment.start_timestamp + 1),
            title: preview_text(&segment.transcript),
            subtitle: Some("ASR transcript".to_string()),
            source: segment.source_id.clone(),
            confidence: segment.confidence.unwrap_or(0.72),
            session_id: Some(segment.session_id.clone()),
            app_name: None,
            window_title: None,
            interaction_state: None,
            reasons: vec![
                "Generated by local Whisper transcription on a finalized speech chunk."
                    .to_string(),
            ],
            visible_windows: Vec::new(),
            ocr_preview: Some(segment.transcript.clone()),
            pii_count: 0,
            evidence_frame_path: None,
            storage_bytes: estimate_asr_segment_storage_bytes(segment),
            storage_exact: true,
            row_count: 1,
            file_count: 0,
            has_detail_view: true,
            tags: vec!["audio".to_string(), "speech".to_string(), "asr".to_string()],
        });
    }

    slices.sort_by_key(|slice| slice.start_timestamp);

    TimelineRailDto::lane(
        "audio_speech",
        "Speech",
        "Durable speaking spans plus transcript markers from local ASR when transcription is available.",
        "Speech state works without transcription. ASR is additive and may be missing while speaking spans still record normally.",
        slices,
    )
}

fn build_audio_emotion_summary_rail(
    speech_emotion_segments: &[SpeechEmotionSegmentDto],
) -> TimelineRailDto {
    let slices = speech_emotion_segments
        .iter()
        .map(|segment| build_emotion_slice("audio_emotion_summary", segment))
        .collect::<Vec<_>>();

    TimelineRailDto::lane(
        "audio_emotion_summary_lane",
        "Overview",
        "Top-level polarity view of speech emotion with positive, negative, neutral, and uncertain segments aligned to the same timeline.",
        "Positive emotions rise above neutral, negative emotions fall below it, and uncertain segments stay visually quiet in this summary view.",
        slices,
    )
}

fn build_audio_emotion_detail_rails(
    speech_emotion_segments: &[SpeechEmotionSegmentDto],
) -> Vec<TimelineRailDto> {
    AUDIO_EMOTION_RAILS
        .iter()
        .map(|(canonical_label, display_label)| {
            let rail_id = format!("audio_emotion_{canonical_label}");
            let slices = speech_emotion_segments
                .iter()
                .filter(|segment| segment.canonical_label == *canonical_label)
                .map(|segment| build_emotion_slice(&rail_id, segment))
                .collect::<Vec<_>>();

            TimelineRailDto::lane(
                &rail_id,
                display_label,
                &format!(
                    "Detailed {} emotion confidence view built from the existing speech-emotion segments.",
                    display_label.to_lowercase()
                ),
                "Each lane shows only one canonical emotion, with height driven directly by the stored confidence for that segment.",
                slices,
            )
        })
        .collect()
}

fn build_audio_sound_events_rail(
    sound_event_spans: &[SoundEventSpanDto],
    sound_event_detections: &[SoundEventDetectionDto],
) -> TimelineRailDto {
    let mut slices = sound_event_spans
        .iter()
        .map(|span| ContextSlice {
            id: span.sound_event_span_id.clone(),
            rail: "audio_sound_events".to_string(),
            slice_kind: "span".to_string(),
            start_timestamp: span.first_seen_at,
            end_timestamp: span.last_seen_at.max(span.first_seen_at + 1),
            title: span.canonical_label.replace('_', " "),
            subtitle: Some(format_duration_short(span.duration_ms)),
            source: span.source_id.clone(),
            confidence: span.avg_confidence,
            session_id: Some(span.session_id.clone()),
            app_name: None,
            window_title: None,
            interaction_state: None,
            reasons: vec![
                "Merged from nearby sound-event detections that shared the same canonical label."
                    .to_string(),
            ],
            visible_windows: Vec::new(),
            ocr_preview: None,
            pii_count: 0,
            evidence_frame_path: None,
            storage_bytes: estimate_sound_event_span_storage_bytes(span),
            storage_exact: false,
            row_count: span.supporting_detection_ids.len() as u64,
            file_count: 0,
            has_detail_view: true,
            tags: vec![
                "audio".to_string(),
                "sound_event".to_string(),
                span.canonical_label.clone(),
            ],
        })
        .collect::<Vec<_>>();

    for detection in sound_event_detections {
        slices.push(ContextSlice {
            id: detection.sound_event_detection_id.clone(),
            rail: "audio_sound_events".to_string(),
            slice_kind: "event".to_string(),
            start_timestamp: detection.start_timestamp,
            end_timestamp: detection.end_timestamp.max(detection.start_timestamp + 1),
            title: detection.canonical_label.replace('_', " "),
            subtitle: Some("Sound event".to_string()),
            source: detection.source_id.clone(),
            confidence: detection.confidence,
            session_id: Some(detection.session_id.clone()),
            app_name: None,
            window_title: None,
            interaction_state: None,
            reasons: vec![format!(
                "Detected by the local sound-event model as {}.",
                detection.event_label
            )],
            visible_windows: Vec::new(),
            ocr_preview: None,
            pii_count: 0,
            evidence_frame_path: None,
            storage_bytes: estimate_sound_event_detection_storage_bytes(detection),
            storage_exact: true,
            row_count: 1,
            file_count: 0,
            has_detail_view: true,
            tags: vec![
                "audio".to_string(),
                "sound_event".to_string(),
                detection.canonical_label.clone(),
            ],
        });
    }

    slices.sort_by_key(|slice| slice.start_timestamp);

    TimelineRailDto::lane(
        "audio_sound_events",
        "Sound Events",
        "Local non-speech audio detections such as impacts, doors, footsteps, vehicles, and other scene sounds.",
        "Sound-event labels are approximate scene-memory cues rather than forensic audio classifications.",
        slices,
    )
}

fn build_emotion_slice(rail_id: &str, segment: &SpeechEmotionSegmentDto) -> ContextSlice {
    let polarity = emotion_polarity(segment.canonical_label.as_str());
    ContextSlice {
        id: segment.speech_emotion_segment_id.clone(),
        rail: rail_id.to_string(),
        slice_kind: "event".to_string(),
        start_timestamp: segment.start_timestamp,
        end_timestamp: segment.end_timestamp.max(segment.start_timestamp + 1),
        title: prettify_emotion_label(&segment.canonical_label),
        subtitle: Some(format!(
            "{} · {}%",
            polarity_label(polarity),
            (segment.confidence * 100.0).round() as i64
        )),
        source: segment.source_id.clone(),
        confidence: segment.confidence,
        session_id: Some(segment.session_id.clone()),
        app_name: None,
        window_title: None,
        interaction_state: None,
        reasons: vec![
            "Inferred from a finalized speech chunk using the local speech-emotion model."
                .to_string(),
        ],
        visible_windows: Vec::new(),
        ocr_preview: None,
        pii_count: 0,
        evidence_frame_path: None,
        storage_bytes: estimate_speech_emotion_storage_bytes(segment),
        storage_exact: true,
        row_count: 1,
        file_count: 0,
        has_detail_view: true,
        tags: vec![
            "audio".to_string(),
            "emotion".to_string(),
            "emotion_summary".to_string(),
            segment.canonical_label.clone(),
            polarity_label(polarity).to_lowercase(),
        ],
    }
}

fn emotion_polarity(label: &str) -> i8 {
    match label {
        "happy" | "surprised" => 1,
        "sad" | "angry" | "fearful" => -1,
        _ => 0,
    }
}

fn polarity_label(polarity: i8) -> &'static str {
    match polarity {
        1 => "Positive",
        -1 => "Negative",
        _ => "Centered",
    }
}

fn prettify_emotion_label(label: &str) -> String {
    label
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
