//! The authorizing device's record of the per-device backup credentials
//! it has issued (§11.4 credential class 1).
//!
//! A device credential is generated by the *authorizing* device at
//! enrollment, delivered inside that device's envelope, and — per §11.4 —
//! "New VK rotations do not change it; it rotates only by re-enrollment."
//! Re-sealing an envelope under a new VK therefore requires the issuer to
//! still know the credential, so it keeps this small VK-sealed record.
//! It holds no other device's keys and never leaves the helper.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use chacha20poly1305::aead::{Aead, KeyInit, Payload};
use chacha20poly1305::{XChaCha20Poly1305, XNonce};
use serde::{Deserialize, Serialize};

use crate::crypto::secret::{random_nonce, SecretBytes};
use crate::crypto::{hex, hkdf};
use crate::errors::ErrorCode;
use crate::storage::store::{write_atomic, WRAPS_DIR};

use super::envelope::DEVICES_DIR;

pub const CREDS_NAME: &str = "creds.bin";
const AAD: &[u8] = b"ov0/device-creds/v1";

#[derive(Debug, Serialize, Deserialize)]
struct CredsFile {
    v: u32,
    nonce: String,
    ct: String,
}

/// device_id → the credential that device was issued.
#[derive(Default)]
pub struct DeviceCreds {
    map: BTreeMap<[u8; 16], [u8; 32]>,
}

pub fn path(dir: &Path) -> PathBuf {
    dir.join(WRAPS_DIR).join(DEVICES_DIR).join(CREDS_NAME)
}

fn cipher(vk: &SecretBytes<32>, vault_id: &[u8; 16]) -> Result<XChaCha20Poly1305, ErrorCode> {
    let key = hkdf::device_creds_key(vk, vault_id).map_err(|_| ErrorCode::Internal)?;
    XChaCha20Poly1305::new_from_slice(key.expose()).map_err(|_| ErrorCode::Internal)
}

impl DeviceCreds {
    /// Read the record. A missing file is an empty record: a vault whose
    /// only device is the Mac has issued nothing yet.
    pub fn load(dir: &Path, vk: &SecretBytes<32>, vault_id: &[u8; 16]) -> Result<Self, ErrorCode> {
        let Ok(bytes) = std::fs::read(path(dir)) else {
            return Ok(DeviceCreds::default());
        };
        let file: CredsFile = serde_json::from_slice(&bytes).map_err(|_| ErrorCode::WrapCorrupt)?;
        if file.v != 1 {
            return Err(ErrorCode::FormatTooNew);
        }
        let nonce: [u8; 24] = hex::decode_array(&file.nonce).ok_or(ErrorCode::WrapCorrupt)?;
        let ct = hex::decode(&file.ct).ok_or(ErrorCode::WrapCorrupt)?;
        let pt = cipher(vk, vault_id)?
            .decrypt(&XNonce::from(nonce), Payload { msg: &ct, aad: AAD })
            .map_err(|_| ErrorCode::WrapCorrupt)?;
        let pt = crate::crypto::secret::SecretVec::new(pt);
        let rows: BTreeMap<String, String> =
            serde_json::from_slice(&pt).map_err(|_| ErrorCode::WrapCorrupt)?;
        let mut map = BTreeMap::new();
        for (id, cred) in rows {
            let id = hex::decode_array::<16>(&id).ok_or(ErrorCode::WrapCorrupt)?;
            let cred = hex::decode_array::<32>(&cred).ok_or(ErrorCode::WrapCorrupt)?;
            map.insert(id, cred);
        }
        Ok(DeviceCreds { map })
    }

    /// Seal to an explicit path (rotation stages `creds.bin.next`).
    pub fn seal_to(
        &self,
        path: &Path,
        vk: &SecretBytes<32>,
        vault_id: &[u8; 16],
    ) -> Result<(), ErrorCode> {
        let rows: BTreeMap<String, String> = self
            .map
            .iter()
            .map(|(id, cred)| (hex::encode(id), hex::encode(cred)))
            .collect();
        let pt = crate::crypto::secret::SecretVec::new(
            serde_json::to_vec(&rows).map_err(|_| ErrorCode::Internal)?,
        );
        let nonce = random_nonce();
        let ct = cipher(vk, vault_id)?
            .encrypt(&XNonce::from(nonce), Payload { msg: &pt, aad: AAD })
            .map_err(|_| ErrorCode::Internal)?;
        let file = CredsFile {
            v: 1,
            nonce: hex::encode(nonce),
            ct: hex::encode(ct),
        };
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|_| ErrorCode::Internal)?;
        }
        write_atomic(path, &serde_json::to_vec(&file).map_err(|_| ErrorCode::Internal)?)
    }

    pub fn save(
        &self,
        dir: &Path,
        vk: &SecretBytes<32>,
        vault_id: &[u8; 16],
    ) -> Result<(), ErrorCode> {
        self.seal_to(&path(dir), vk, vault_id)
    }

    pub fn insert(&mut self, device_id: [u8; 16], cred: &SecretBytes<32>) {
        self.map.insert(device_id, *cred.expose());
    }

    pub fn get(&self, device_id: &[u8; 16]) -> Option<SecretBytes<32>> {
        self.map.get(device_id).map(|c| SecretBytes::new(*c))
    }

    pub fn remove(&mut self, device_id: &[u8; 16]) {
        self.map.remove(device_id);
    }

    pub fn ids(&self) -> Vec<[u8; 16]> {
        self.map.keys().copied().collect()
    }

    pub fn len(&self) -> usize {
        self.map.len()
    }

    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }
}

impl Drop for DeviceCreds {
    fn drop(&mut self) {
        use zeroize::Zeroize;
        for cred in self.map.values_mut() {
            cred.zeroize();
        }
    }
}
